# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92578fa1b4bd9feb81212c6260317699790a843075bb0b1dbbdaaec2bcec22c628a4bb1f09fc128edc5d8271f83a55779e4b9bdd39f82e9ae0bf83af43f967bd

test:
  secret_key_base: d8b18a30f3e5f5bc37eb67ddbff1cba3af6599bcf6d9cd6dcf5f75ec16233d6808c3bf70aff6c3e8116117d27ca0851412a3c97cf72a42a41119ca32cffd8f68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
